#[allow(unused_imports)]
use tracing::{debug, error, info, trace, warn};

pub mod command;

#[path = "grpc.hello.v1.rs"] // generated by protoc
pub mod hello;

pub fn go(cmd: &command::Command) {
    info!("grpc go with command: {:?}", cmd);
}
